# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-quegay.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1280, 747)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget{background:color: #F3F6F5}")
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget{background-color: #F3F6F5;}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, -1, 1281, 793))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(320, 791))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: #052034;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 340, 301, 598))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #f3f6f5;")
        self.label.setLineWidth(0)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignVCenter)
        self.refreshButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.refreshButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshButton.sizePolicy().hasHeightForWidth())
        self.refreshButton.setSizePolicy(sizePolicy)
        self.refreshButton.setMinimumSize(QtCore.QSize(100, 30))
        self.refreshButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.refreshButton.setFont(font)
        self.refreshButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refreshButton.setStyleSheet("QPushButton{\n"
"    background-color: #025D79;\n"
"     border-radius: 15px;\n"
"  color: #f3f6f5;}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #027CA1;\n"
" }\n"
"\n"
"QPushButton:disabled,\n"
"QPushButton[disabled]{\n"
"  color: light gray;\n"
"}")
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.portComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.portComboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portComboBox.sizePolicy().hasHeightForWidth())
        self.portComboBox.setSizePolicy(sizePolicy)
        self.portComboBox.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.portComboBox.setFont(font)
        self.portComboBox.setStyleSheet("QComboBox{border-radius:15px; background-color: #022B3B;  color: #f3f6f5;}\n"
"\n"
"QComboBox:disabled,\n"
"QComboBox[disabled]{\n"
"  color: light gray;\n"
"}")
        self.portComboBox.setIconSize(QtCore.QSize(39, 26))
        self.portComboBox.setFrame(False)
        self.portComboBox.setObjectName("portComboBox")
        self.portComboBox.addItem("")
        self.portComboBox.addItem("")
        self.verticalLayout.addWidget(self.portComboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #f3f6f5;")
        self.label_2.setLineWidth(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.emailTestButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.emailTestButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailTestButton.sizePolicy().hasHeightForWidth())
        self.emailTestButton.setSizePolicy(sizePolicy)
        self.emailTestButton.setMinimumSize(QtCore.QSize(100, 30))
        self.emailTestButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.emailTestButton.setFont(font)
        self.emailTestButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.emailTestButton.setStyleSheet("QPushButton{\n"
"    background-color: #025D79;\n"
"     border-radius: 15px;\n"
"  color: #f3f6f5;}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #027CA1;\n"
" }\n"
"\n"
"QPushButton:disabled,\n"
"QPushButton[disabled]{\n"
"  color: light gray;\n"
"}")
        self.emailTestButton.setObjectName("emailTestButton")
        self.horizontalLayout_2.addWidget(self.emailTestButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox.setEnabled(True)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox.setStyleSheet("QCheckBox{ color: #f3f6f5;}\n"
"QCheckBox:disabled,\n"
"QCheckBox[disabled]{\n"
"  color: light gray;\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.emailField = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.emailField.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailField.sizePolicy().hasHeightForWidth())
        self.emailField.setSizePolicy(sizePolicy)
        self.emailField.setMinimumSize(QtCore.QSize(0, 30))
        self.emailField.setStyleSheet("QLineEdit{background-color: #022B3B; border-radius:15px}\n"
"\n"
"QLineEdit::enabled{color: #f3f6f5;}")
        self.emailField.setObjectName("emailField")
        self.horizontalLayout_3.addWidget(self.emailField)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.connectButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.connectButton.setFont(font)
        self.connectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connectButton.setStyleSheet("QPushButton{\n"
"    background-color: #025D79;\n"
"     border-radius: 15px;\n"
"  color: #f3f6f5;}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #027CA1;\n"
" }")
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(76, 20))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"     border-radius: 10px;\n"
"     background-color: #022B3B;\n"
"    color: #f3f6f5;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: #025D79;\n"
"    border-radius: 10px\n"
"}")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.resultsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsLabel.sizePolicy().hasHeightForWidth())
        self.resultsLabel.setSizePolicy(sizePolicy)
        self.resultsLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resultsLabel.setFont(font)
        self.resultsLabel.setStyleSheet("color: #F3F6F5;")
        self.resultsLabel.setLineWidth(0)
        self.resultsLabel.setText("")
        self.resultsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.resultsLabel.setObjectName("resultsLabel")
        self.verticalLayout.addWidget(self.resultsLabel)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(10, 10, 311, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(7, 127))
        self.logo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/newPrefix/logo-2.png"))
        self.logo.setObjectName("logo")
        self.horizontalLayout_4.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("QWidget{background-color:#022B3B; font-size:16px}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 941, 731))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        date_axis = pg.graphicsItems.DateAxisItem.DateAxisItem(orientation = 'bottom')
        self.graphWidget = PlotWidget(self.gridLayoutWidget,
                                      title="Resistance Measurement",
                                      axisItems = {'bottom': date_axis}
                                      )
        self.graphWidget.setMouseEnabled(x=False, y=False)
        self.graphWidget.setBackground(None)
        self.graphWidget.setObjectName("graphWidget")

        #First axis setup
        self.plotLine = self.graphWidget.plot(pen = pg.mkPen(color='#027CA1', width=3))
        self.graphWidget.showAxis('left')
        self.graphWidget.setLabel('left', 'Resistance', units="<font>&Omega;</font>",
                                  color='#027CA1', **{'font-size':'14pt'})
        self.graphWidget.getAxis('left').enableAutoSIPrefix(False)
        #Second axis setup
        self.graphWidget.showAxis('right')
        self.graphWidget.setLabel('right', 'Frequency', units="<font>Hz</font>",
                   color='#FF8811', **{'font-size':'14pt'})
        # self.graphWidget.getAxis('right').setPen(pg.mkPen(color='#F3F6F5', width=3))

        self.twinGraph = pg.ViewBox()
        self.graphWidget.scene().addItem(self.twinGraph)
        self.graphWidget.getAxis('right').linkToView(self.twinGraph)
        self.twinGraph.setXLink(self.graphWidget)

        self.twinLine = pg.PlotCurveItem(pen = pg.mkPen(color='#FF8811',width=3))
        self.twinGraph.addItem(self.twinLine)

        self.gridLayout.addWidget(self.graphWidget, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.checkBox.toggled['bool'].connect(self.emailField.setEnabled)
        self.connectButton.clicked.connect(self.connectButton.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QCM Contamination Detector"))
        self.label.setText(_translate("MainWindow", "Connection Port"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.portComboBox.setItemText(0, _translate("MainWindow", "item 1"))
        self.portComboBox.setItemText(1, _translate("MainWindow", "item 2"))
        self.label_2.setText(_translate("MainWindow", "Email Notification"))
        self.emailTestButton.setText(_translate("MainWindow", "Test Email"))
        self.checkBox.setText(_translate("MainWindow", "Enabled"))
        self.emailField.setPlaceholderText(_translate("MainWindow", "Email Address"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.actionquit.setText(_translate("MainWindow", "Save Data"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
from pyqtgraph import PlotWidget
import pyqtgraph as pg
from interface import ui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
